from app.domain.cash_register import CashRegisterSession, CashRegisterStatus
from app.domain.catalog import Category, Product
from app.domain.exceptions import (
    AppAuthenticationError,
    AppConflictError,
    AppError,
    AppNotFoundError,
    AppPermissionError,
    AppValidationError,
    AuthenticationRequiredError,
    CashRegisterAlreadyClosedError,
    CashRegisterAlreadyOpenError,
    CashRegisterError,
    CashRegisterNotFoundError,
    CashRegisterNotOpenError,
    CategoryNotFoundError,
    DuplicateCategoryNameError,
    DuplicateUsernameError,
    ExpenseImmutableError,
    ExpenseNotFoundError,
    InvalidCredentialsError,
    InvalidExpenseAmountError,
    InvalidOwnerPinError,
    InvalidPaymentError,
    OwnerPermissionRequiredError,
    ProductInactiveError,
    ProductNotFoundError,
    UserNotFoundError,
    UserRegistrationNotAllowedError,
)
from app.domain.expense import Expense, ExpenseCategory
from app.domain.sale import PaymentBreakdown, PaymentMethod, Sale, SaleItem, SaleStatus
from app.domain.sync_queue import SyncQueueEntry, SyncStatus
from app.domain.user import User, UserRole, UserSession

__all__ = [
    "AppAuthenticationError",
    "AppConflictError",
    "AppError",
    "AppNotFoundError",
    "AppPermissionError",
    "AppValidationError",
    "AuthenticationRequiredError",
    "Category",
    "CategoryNotFoundError",
    "CashRegisterAlreadyClosedError",
    "CashRegisterAlreadyOpenError",
    "CashRegisterError",
    "CashRegisterNotFoundError",
    "CashRegisterNotOpenError",
    "CashRegisterSession",
    "CashRegisterStatus",
    "DuplicateCategoryNameError",
    "DuplicateUsernameError",
    "Expense",
    "ExpenseCategory",
    "ExpenseImmutableError",
    "ExpenseNotFoundError",
    "InvalidCredentialsError",
    "InvalidExpenseAmountError",
    "InvalidOwnerPinError",
    "InvalidPaymentError",
    "OwnerPermissionRequiredError",
    "PaymentBreakdown",
    "PaymentMethod",
    "Product",
    "ProductInactiveError",
    "ProductNotFoundError",
    "Sale",
    "SaleItem",
    "SaleStatus",
    "SyncQueueEntry",
    "SyncStatus",
    "User",
    "UserNotFoundError",
    "UserRegistrationNotAllowedError",
    "UserRole",
    "UserSession",
]
